package org.plutodjava.matchmaker.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.plutodjava.matchmaker.db.domain.TbAdmin;
import org.plutodjava.matchmaker.db.domain.TbAdminExample;

public interface TbAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    long countByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int deleteByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int insert(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int insertSelective(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    TbAdmin selectOneByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    TbAdmin selectOneByExampleSelective(@Param("example") TbAdminExample example, @Param("selective") TbAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    List<TbAdmin> selectByExampleSelective(@Param("example") TbAdminExample example, @Param("selective") TbAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    List<TbAdmin> selectByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    TbAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    TbAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    TbAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbAdmin record, @Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbAdmin record, @Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}