package org.plutodjava.matchmaker.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.plutodjava.matchmaker.db.domain.TbFlippedMobileGroup;
import org.plutodjava.matchmaker.db.domain.TbFlippedMobileGroupExample;

public interface TbFlippedMobileGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    long countByExample(TbFlippedMobileGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int deleteByExample(TbFlippedMobileGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int insert(TbFlippedMobileGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int insertSelective(TbFlippedMobileGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    TbFlippedMobileGroup selectOneByExample(TbFlippedMobileGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    TbFlippedMobileGroup selectOneByExampleSelective(@Param("example") TbFlippedMobileGroupExample example, @Param("selective") TbFlippedMobileGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    List<TbFlippedMobileGroup> selectByExampleSelective(@Param("example") TbFlippedMobileGroupExample example, @Param("selective") TbFlippedMobileGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    List<TbFlippedMobileGroup> selectByExample(TbFlippedMobileGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    TbFlippedMobileGroup selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbFlippedMobileGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    TbFlippedMobileGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    TbFlippedMobileGroup selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFlippedMobileGroup record, @Param("example") TbFlippedMobileGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFlippedMobileGroup record, @Param("example") TbFlippedMobileGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFlippedMobileGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFlippedMobileGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TbFlippedMobileGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}