package org.plutodjava.matchmaker.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.plutodjava.matchmaker.db.domain.TbSystem;
import org.plutodjava.matchmaker.db.domain.TbSystemExample;

public interface TbSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    long countByExample(TbSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int deleteByExample(TbSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int insert(TbSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int insertSelective(TbSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    TbSystem selectOneByExample(TbSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    TbSystem selectOneByExampleSelective(@Param("example") TbSystemExample example, @Param("selective") TbSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    List<TbSystem> selectByExampleSelective(@Param("example") TbSystemExample example, @Param("selective") TbSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    List<TbSystem> selectByExample(TbSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    TbSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    TbSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    TbSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbSystem record, @Param("example") TbSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbSystem record, @Param("example") TbSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TbSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}