package org.plutodjava.matchmaker.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.plutodjava.matchmaker.db.domain.TbUserIntention;
import org.plutodjava.matchmaker.db.domain.TbUserIntentionExample;

public interface TbUserIntentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    long countByExample(TbUserIntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    int deleteByExample(TbUserIntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    int insert(TbUserIntention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    int insertSelective(TbUserIntention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    TbUserIntention selectOneByExample(TbUserIntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    TbUserIntention selectOneByExampleSelective(@Param("example") TbUserIntentionExample example, @Param("selective") TbUserIntention.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    List<TbUserIntention> selectByExampleSelective(@Param("example") TbUserIntentionExample example, @Param("selective") TbUserIntention.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    List<TbUserIntention> selectByExample(TbUserIntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    TbUserIntention selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbUserIntention.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    TbUserIntention selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbUserIntention record, @Param("example") TbUserIntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbUserIntention record, @Param("example") TbUserIntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbUserIntention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbUserIntention record);
}