package org.plutodjava.matchmaker.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TbFlippedMobileGroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public TbFlippedMobileGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public TbFlippedMobileGroupExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public TbFlippedMobileGroupExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        TbFlippedMobileGroupExample example = new TbFlippedMobileGroupExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public TbFlippedMobileGroupExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public TbFlippedMobileGroupExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFlippedMobileIsNull() {
            addCriterion("flipped_mobile is null");
            return (Criteria) this;
        }

        public Criteria andFlippedMobileIsNotNull() {
            addCriterion("flipped_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andFlippedMobileEqualTo(String value) {
            addCriterion("flipped_mobile =", value, "flippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andFlippedMobileEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("flipped_mobile = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFlippedMobileNotEqualTo(String value) {
            addCriterion("flipped_mobile <>", value, "flippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andFlippedMobileNotEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("flipped_mobile <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFlippedMobileGreaterThan(String value) {
            addCriterion("flipped_mobile >", value, "flippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andFlippedMobileGreaterThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("flipped_mobile > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFlippedMobileGreaterThanOrEqualTo(String value) {
            addCriterion("flipped_mobile >=", value, "flippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andFlippedMobileGreaterThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("flipped_mobile >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFlippedMobileLessThan(String value) {
            addCriterion("flipped_mobile <", value, "flippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andFlippedMobileLessThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("flipped_mobile < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFlippedMobileLessThanOrEqualTo(String value) {
            addCriterion("flipped_mobile <=", value, "flippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andFlippedMobileLessThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("flipped_mobile <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFlippedMobileLike(String value) {
            addCriterion("flipped_mobile like", value, "flippedMobile");
            return (Criteria) this;
        }

        public Criteria andFlippedMobileNotLike(String value) {
            addCriterion("flipped_mobile not like", value, "flippedMobile");
            return (Criteria) this;
        }

        public Criteria andFlippedMobileIn(List<String> values) {
            addCriterion("flipped_mobile in", values, "flippedMobile");
            return (Criteria) this;
        }

        public Criteria andFlippedMobileNotIn(List<String> values) {
            addCriterion("flipped_mobile not in", values, "flippedMobile");
            return (Criteria) this;
        }

        public Criteria andFlippedMobileBetween(String value1, String value2) {
            addCriterion("flipped_mobile between", value1, value2, "flippedMobile");
            return (Criteria) this;
        }

        public Criteria andFlippedMobileNotBetween(String value1, String value2) {
            addCriterion("flipped_mobile not between", value1, value2, "flippedMobile");
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileIsNull() {
            addCriterion("by_flipped_mobile is null");
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileIsNotNull() {
            addCriterion("by_flipped_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileEqualTo(String value) {
            addCriterion("by_flipped_mobile =", value, "byFlippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andByFlippedMobileEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("by_flipped_mobile = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileNotEqualTo(String value) {
            addCriterion("by_flipped_mobile <>", value, "byFlippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andByFlippedMobileNotEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("by_flipped_mobile <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileGreaterThan(String value) {
            addCriterion("by_flipped_mobile >", value, "byFlippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andByFlippedMobileGreaterThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("by_flipped_mobile > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileGreaterThanOrEqualTo(String value) {
            addCriterion("by_flipped_mobile >=", value, "byFlippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andByFlippedMobileGreaterThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("by_flipped_mobile >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileLessThan(String value) {
            addCriterion("by_flipped_mobile <", value, "byFlippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andByFlippedMobileLessThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("by_flipped_mobile < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileLessThanOrEqualTo(String value) {
            addCriterion("by_flipped_mobile <=", value, "byFlippedMobile");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andByFlippedMobileLessThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("by_flipped_mobile <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileLike(String value) {
            addCriterion("by_flipped_mobile like", value, "byFlippedMobile");
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileNotLike(String value) {
            addCriterion("by_flipped_mobile not like", value, "byFlippedMobile");
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileIn(List<String> values) {
            addCriterion("by_flipped_mobile in", values, "byFlippedMobile");
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileNotIn(List<String> values) {
            addCriterion("by_flipped_mobile not in", values, "byFlippedMobile");
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileBetween(String value1, String value2) {
            addCriterion("by_flipped_mobile between", value1, value2, "byFlippedMobile");
            return (Criteria) this;
        }

        public Criteria andByFlippedMobileNotBetween(String value1, String value2) {
            addCriterion("by_flipped_mobile not between", value1, value2, "byFlippedMobile");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(LocalDateTime value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andAddTimeEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("add_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(LocalDateTime value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andAddTimeNotEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("add_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(LocalDateTime value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("add_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("add_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(LocalDateTime value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("add_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("add_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<LocalDateTime> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<LocalDateTime> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andDeletedEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andDeletedNotEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andApplyIsNull() {
            addCriterion("apply is null");
            return (Criteria) this;
        }

        public Criteria andApplyIsNotNull() {
            addCriterion("apply is not null");
            return (Criteria) this;
        }

        public Criteria andApplyEqualTo(Boolean value) {
            addCriterion("apply =", value, "apply");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andApplyEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("apply = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApplyNotEqualTo(Boolean value) {
            addCriterion("apply <>", value, "apply");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andApplyNotEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("apply <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApplyGreaterThan(Boolean value) {
            addCriterion("apply >", value, "apply");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andApplyGreaterThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("apply > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApplyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("apply >=", value, "apply");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andApplyGreaterThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("apply >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApplyLessThan(Boolean value) {
            addCriterion("apply <", value, "apply");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andApplyLessThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("apply < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApplyLessThanOrEqualTo(Boolean value) {
            addCriterion("apply <=", value, "apply");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andApplyLessThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("apply <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApplyIn(List<Boolean> values) {
            addCriterion("apply in", values, "apply");
            return (Criteria) this;
        }

        public Criteria andApplyNotIn(List<Boolean> values) {
            addCriterion("apply not in", values, "apply");
            return (Criteria) this;
        }

        public Criteria andApplyBetween(Boolean value1, Boolean value2) {
            addCriterion("apply between", value1, value2, "apply");
            return (Criteria) this;
        }

        public Criteria andApplyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("apply not between", value1, value2, "apply");
            return (Criteria) this;
        }

        public Criteria andHandIsNull() {
            addCriterion("hand is null");
            return (Criteria) this;
        }

        public Criteria andHandIsNotNull() {
            addCriterion("hand is not null");
            return (Criteria) this;
        }

        public Criteria andHandEqualTo(Boolean value) {
            addCriterion("hand =", value, "hand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andHandEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("hand = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHandNotEqualTo(Boolean value) {
            addCriterion("hand <>", value, "hand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andHandNotEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("hand <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHandGreaterThan(Boolean value) {
            addCriterion("hand >", value, "hand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andHandGreaterThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("hand > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHandGreaterThanOrEqualTo(Boolean value) {
            addCriterion("hand >=", value, "hand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andHandGreaterThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("hand >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHandLessThan(Boolean value) {
            addCriterion("hand <", value, "hand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andHandLessThanColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("hand < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHandLessThanOrEqualTo(Boolean value) {
            addCriterion("hand <=", value, "hand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andHandLessThanOrEqualToColumn(TbFlippedMobileGroup.Column column) {
            addCriterion(new StringBuilder("hand <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHandIn(List<Boolean> values) {
            addCriterion("hand in", values, "hand");
            return (Criteria) this;
        }

        public Criteria andHandNotIn(List<Boolean> values) {
            addCriterion("hand not in", values, "hand");
            return (Criteria) this;
        }

        public Criteria andHandBetween(Boolean value1, Boolean value2) {
            addCriterion("hand between", value1, value2, "hand");
            return (Criteria) this;
        }

        public Criteria andHandNotBetween(Boolean value1, Boolean value2) {
            addCriterion("hand not between", value1, value2, "hand");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        private TbFlippedMobileGroupExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        protected Criteria(TbFlippedMobileGroupExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public TbFlippedMobileGroupExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(TbFlippedMobileGroup.Deleted.IS_DELETED.value()) : andDeletedNotEqualTo(TbFlippedMobileGroup.Deleted.IS_DELETED.value());
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table tb_flipped_mobile_group
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_flipped_mobile_group
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_flipped_mobile_group
         *
         * @mbg.generated
         */
        void example(org.plutodjava.matchmaker.db.domain.TbFlippedMobileGroupExample example);
    }
}