package org.plutodjava.matchmaker.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class TbUserIntention {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.age_range
     *
     * @mbg.generated
     */
    private String ageRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.minimum_education
     *
     * @mbg.generated
     */
    private String minimumEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.height_range
     *
     * @mbg.generated
     */
    private String heightRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.weight_range
     *
     * @mbg.generated
     */
    private String weightRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.income_range
     *
     * @mbg.generated
     */
    private String incomeRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.place
     *
     * @mbg.generated
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.marriage
     *
     * @mbg.generated
     */
    private String marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_intention.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.id
     *
     * @return the value of tb_user_intention.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.id
     *
     * @param id the value for tb_user_intention.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.user_id
     *
     * @return the value of tb_user_intention.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.user_id
     *
     * @param userId the value for tb_user_intention.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.age_range
     *
     * @return the value of tb_user_intention.age_range
     *
     * @mbg.generated
     */
    public String getAgeRange() {
        return ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.age_range
     *
     * @param ageRange the value for tb_user_intention.age_range
     *
     * @mbg.generated
     */
    public void setAgeRange(String ageRange) {
        this.ageRange = ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.minimum_education
     *
     * @return the value of tb_user_intention.minimum_education
     *
     * @mbg.generated
     */
    public String getMinimumEducation() {
        return minimumEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.minimum_education
     *
     * @param minimumEducation the value for tb_user_intention.minimum_education
     *
     * @mbg.generated
     */
    public void setMinimumEducation(String minimumEducation) {
        this.minimumEducation = minimumEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.height_range
     *
     * @return the value of tb_user_intention.height_range
     *
     * @mbg.generated
     */
    public String getHeightRange() {
        return heightRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.height_range
     *
     * @param heightRange the value for tb_user_intention.height_range
     *
     * @mbg.generated
     */
    public void setHeightRange(String heightRange) {
        this.heightRange = heightRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.weight_range
     *
     * @return the value of tb_user_intention.weight_range
     *
     * @mbg.generated
     */
    public String getWeightRange() {
        return weightRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.weight_range
     *
     * @param weightRange the value for tb_user_intention.weight_range
     *
     * @mbg.generated
     */
    public void setWeightRange(String weightRange) {
        this.weightRange = weightRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.industry
     *
     * @return the value of tb_user_intention.industry
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.industry
     *
     * @param industry the value for tb_user_intention.industry
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.income_range
     *
     * @return the value of tb_user_intention.income_range
     *
     * @mbg.generated
     */
    public String getIncomeRange() {
        return incomeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.income_range
     *
     * @param incomeRange the value for tb_user_intention.income_range
     *
     * @mbg.generated
     */
    public void setIncomeRange(String incomeRange) {
        this.incomeRange = incomeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.place
     *
     * @return the value of tb_user_intention.place
     *
     * @mbg.generated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.place
     *
     * @param place the value for tb_user_intention.place
     *
     * @mbg.generated
     */
    public void setPlace(String place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.marriage
     *
     * @return the value of tb_user_intention.marriage
     *
     * @mbg.generated
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.marriage
     *
     * @param marriage the value for tb_user_intention.marriage
     *
     * @mbg.generated
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.add_time
     *
     * @return the value of tb_user_intention.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.add_time
     *
     * @param addTime the value for tb_user_intention.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_intention.update_time
     *
     * @return the value of tb_user_intention.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_intention.update_time
     *
     * @param updateTime the value for tb_user_intention.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", ageRange=").append(ageRange);
        sb.append(", minimumEducation=").append(minimumEducation);
        sb.append(", heightRange=").append(heightRange);
        sb.append(", weightRange=").append(weightRange);
        sb.append(", industry=").append(industry);
        sb.append(", incomeRange=").append(incomeRange);
        sb.append(", place=").append(place);
        sb.append(", marriage=").append(marriage);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbUserIntention other = (TbUserIntention) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAgeRange() == null ? other.getAgeRange() == null : this.getAgeRange().equals(other.getAgeRange()))
            && (this.getMinimumEducation() == null ? other.getMinimumEducation() == null : this.getMinimumEducation().equals(other.getMinimumEducation()))
            && (this.getHeightRange() == null ? other.getHeightRange() == null : this.getHeightRange().equals(other.getHeightRange()))
            && (this.getWeightRange() == null ? other.getWeightRange() == null : this.getWeightRange().equals(other.getWeightRange()))
            && (this.getIndustry() == null ? other.getIndustry() == null : this.getIndustry().equals(other.getIndustry()))
            && (this.getIncomeRange() == null ? other.getIncomeRange() == null : this.getIncomeRange().equals(other.getIncomeRange()))
            && (this.getPlace() == null ? other.getPlace() == null : this.getPlace().equals(other.getPlace()))
            && (this.getMarriage() == null ? other.getMarriage() == null : this.getMarriage().equals(other.getMarriage()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAgeRange() == null) ? 0 : getAgeRange().hashCode());
        result = prime * result + ((getMinimumEducation() == null) ? 0 : getMinimumEducation().hashCode());
        result = prime * result + ((getHeightRange() == null) ? 0 : getHeightRange().hashCode());
        result = prime * result + ((getWeightRange() == null) ? 0 : getWeightRange().hashCode());
        result = prime * result + ((getIndustry() == null) ? 0 : getIndustry().hashCode());
        result = prime * result + ((getIncomeRange() == null) ? 0 : getIncomeRange().hashCode());
        result = prime * result + ((getPlace() == null) ? 0 : getPlace().hashCode());
        result = prime * result + ((getMarriage() == null) ? 0 : getMarriage().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table tb_user_intention
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        ageRange("age_range", "ageRange", "VARCHAR", false),
        minimumEducation("minimum_education", "minimumEducation", "VARCHAR", false),
        heightRange("height_range", "heightRange", "VARCHAR", false),
        weightRange("weight_range", "weightRange", "VARCHAR", false),
        industry("industry", "industry", "VARCHAR", false),
        incomeRange("income_range", "incomeRange", "VARCHAR", false),
        place("place", "place", "VARCHAR", false),
        marriage("marriage", "marriage", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_user_intention
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}